Teme/tema14nou/site_programari/programari/urls.py
from django.urls import path
from . import views

# urlpatterns = [
#     # path("", views.index, name="programari"),
#     path("<int:client_id>", views.client_details, name="client_details"),
#     path("client", views.client_add, name="add"),
#     path("", views.employees, name="all_employees"),
#     path("<int:employee_id>", views.employee_detail, name="employee_details"),
#     path("employee", views.employee_add, name="add"),
#     path("", views.services, name="all_services_"),
#     path("<int:service_id>", views.service_details, name="service_details"),
#     path("service", views.service_add, name="add"),
#     path("", views.appointments, name="all_appointments"),
#     path("<int:appointment_id>", views.appointment_details, name="appointment_details"),
#     path("appointment", views.appointment_add, name="add")
#
 # ]



urlpatterns = [
     path("", views.index, name="programari"),
     path("", views.ClientsView.as_view(), name="all_clients"),
     path("<int:pk>", views.ClientDetailView.as_view(), name="client_detail"),
     path("client", views.ClientCreateView.as_view(), name="add"),
     path("", views.AppointmentsView.as_view(), name="all_appointments"),
     path("<int:pk>", views.AppointmentDetailView.as_view(), name="appointment_detail"),
     path("appointment", views.AppointmentCreateView.as_view(), name="add"),
     path("", views.ServicesView.as_view(), name="all_services"),
     path("<int:pk>", views.ServiceDetailView.as_view(), name="service_detail"),
     path("pet", views.ServiceCreateView.as_view(), name="add"),
     path("", views.EmployeesView.as_view(), name="all_employees"),
     path("<int:pk>", views.EmployeeDetailView.as_view(), name="employee_detail"),
     path("pet", views.EmployeeCreateView.as_view(), name="add")
]

app_name = "programari"

Teme/tema14nou/site_programari/site_programari/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("programari/", include("programari.urls"))
]

Teme/tema14nou/site_programari/programari/models.py
from django.db import models

# Create your models here.
class Client(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Employee(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    specialty = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class Service(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return self.name


class Appointment(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    date = models.DateTimeField()

    def __str__(self):
        return f'{self.client} - {self.service} - {self.date}'

Teme/tema14nou/site_programari/programari/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from .models import Client, Employee, Service, Appointment


# Create your views here.
def index(request):
    return HttpResponse("Aici vom avea programarile!!!!!")


# def clients(request):
#     clients_list = Client.objects.all()
#     return render(request, 'all_clients.html', {'clients': clients_list})
#
#
# def client_details(request, client_id):
#     client = get_object_or_404(Client, pk=client_id)
#     return render(request, "client_detail.html", {"client": client})
#
#
# def client_add(request):
#     client_details = request.POST.dict()
#     client = Client(first_name=client_details["first_name"], last_name = client_details["last_name"], email = client_details["email"], phone = client_details["phone"], address = client_details["address"])
#     client.save()
#     return HttpResponseRedirect(reverse("clients:all_clients"))
#
#
# def employees(request):
#     employees_list = Employee.objects.all()
#     return render(request, 'all_employees.html', {'employees': employees_list})
#
#
# def employee_detail(request, employee_id):
#     employee = get_object_or_404(Employee, pk=employee_id)
#     return render(request, "employee_detail.html", {"employee": employee})
#
#
# def employee_add(request):
#     employee_detail = request.POST.dict()
#     employee = Employee(first_name=employee_detail["first_name"], last_name=employee_detail["last_name"], email=employee_detail["email"], phone=employee_detail["phone"], speciality=employee_detail["speciality"])
#     employee.save()
#     return HttpResponseRedirect(reverse("employees:all_employees"))
#
#
# def services(request):
#     services_list = Service.objects.all()
#     return render(request, 'all_services.html', {'services': services_list})
#
#
# def service_details(request, service_id):
#     service = get_object_or_404(Service, pk=service_id)
#     return render(request, "service_detail.html", {"service": service})
#
#
# def service_add(request):
#     service_details = request.POST.dict()
#     service = Service(name=service_details["name"], description=service_details["description"],price=service_details["price"])
#     service.save()
#     return HttpResponseRedirect(reverse("service:all_services"))
#
#
# def appointments(request):
#     appointments_list = Appointment.objects.all()
#     return render(request, 'all_appointment.html', {'appointments': appointments_list})
#
#
# def appointment_details(request, appointment_id):
#     appointment = get_object_or_404(Appointment, pk=appointment_id)
#     return render(request, "appointment_detail.html", {"appointment": appointment})
#
#
# def appointment_add(request):
#     appointment_details = request.POST.dict()
#     appointment = Appointment(client=appointment_details["client"], employee=appointment_details["last_name"],service=appointment_details["service"], date=appointment_details["date"])
#     appointment.save()
#     return HttpResponseRedirect(reverse("appointments:all_appointments"))


class AppointmentsView(generic.ListView):
    template_name = "all_appointments.html"
    context_object_name = "appointments"

    def get_queryset(self):
        return Appointment.objects.all()


class AppointmentDetailView(generic.DetailView):
    template_name = "appointment_detail.html"
    model = Appointment


class AppointmentCreateView(generic.CreateView):
    model = Appointment
    fields = ["client", "employee", "service", "date"]
    success_url = reverse_lazy("appointments:all_appointments")


class ClientsView(generic.ListView):
    template_name = "all_clients.html"
    context_object_name = "clients"

    def get_queryset(self):
        return Client.objects.all()


class ClientDetailView(generic.DetailView):
    template_name = "client_detail.html"
    model = Client


class ClientCreateView(generic.CreateView):
    model = Client
    fields = ["first_name", "last_name", "email", "phone", "address"]
    success_url = reverse_lazy("clients:all_clients")

class EmployeesView(generic.ListView):
    template_name = "all_employees.html"
    context_object_name = "employees"

    def get_queryset(self):
        return Employee.objects.all()


class EmployeeDetailView(generic.DetailView):
    template_name = "employee_detail.html"
    model = Employee


class EmployeeCreateView(generic.CreateView):
    model = Employee
    fields = ["first_name", "last_name", "email", "phone", "speciality"]
    success_url = reverse_lazy("employees:all_employees")

class ServicesView(generic.ListView):
    template_name = "all_services.html"
    context_object_name = "services"

    def get_queryset(self):
        return Service.objects.all()


class ServiceDetailView(generic.DetailView):
    template_name = "service_detail.html"
    model = Service


class ServiceCreateView(generic.CreateView):
    model = Service
    fields = ["name", "description", "price"]
    success_url = reverse_lazy("services:all_services")

Teme/tema14nou/site_programari/programari/templates/all_appointments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Appointments</title>
</head>
<body>
{% if appointment %}
<h2>
    All Appointments

</h2>
<div class ="all_appointments-list">
    <ul>
        {% for appointment in appointments %}
        <li>
            <a href="{% url 'appointments:appointment_detail' appointment.id %}"> {{ appointment }}</a>
        </li>
        {% endfor %}
    </ul>
    </div>
{% include "form.html" %}
{% endif %}
</body>
</html>

Teme/tema14nou/site_programari/programari/templates/all_clients.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Clients</title>
</head>
<body>
{% if client %}
<h2>
    All Clients

</h2>
<div class ="all_clients-list">
    <ul>
        {% for client in clients %}
        <li>
            <a href="{% url 'clients:client_detail' client.id %}"> {{ client }}</a>
        </li>
        {% endfor %}
    </ul>
    </div>
{% include "form.html" %}
{% endif %}
</body>
</html>

Teme/tema14nou/site_programari/programari/templates/all_employees.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employees</title>
</head>
<body>
{% if employee %}
<h2>
    All Employees

</h2>
<div class ="all_employees-list">
    <ul>
        {% for employee in employees %}
        <li>
            <a href="{% url 'employees:employee_detail' employee.id %}"> {{ employee }}</a>
        </li>
        {% endfor %}
    </ul>
    </div>
{% include "form.html" %}
{% endif %}
</body>
</html>

Teme/tema14nou/site_programari/programari/templates/all_services.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Services</title>
</head>
<body>
{% if service %}
<h2>
    All Services

</h2>
<div class ="all_services-list">
    <ul>
        {% for service in services %}
        <li>
            <a href="{% url 'services:service_detail' service.id %}"> {{ service }}</a>
        </li>
        {% endfor %}
    </ul>
    </div>
{% include "form.html" %}
{% endif %}
</body>
</html>

Teme/tema14nou/site_programari/programari/templates/appointment_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ appointment.name }}</title>
</head>
<body>
{{ appointment }}
</body>
</html>

Teme/tema14nou/site_programari/programari/templates/client_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ client.name }}</title>
</head>
<body>
{{ client }}
</body>
</html>

Teme/tema14nou/site_programari/programari/templates/employee_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ employee.name }}</title>
</head>
<body>
{{ employee }}
</body>
</html>

Teme/tema14nou/site_programari/programari/templates/form.html
<form action="{% url 'programari:add' %}" method="post">
  {% csrf_token %}
  <fieldset>
     <label for="first name">
         First Name:
     </label>
    <input type="text" name="first name" id="first name"><br>
    <label for="last name">
        Last Name:
    </label>
    <input type="text" name="last name" id="last name"><br>
    <label for="email">
        Email:
    </label>
    <input type="text" name="email" id="email"><br>
    <label for="phone">
        Phone:
    </label>
    <input type="number" name="phone" id="phone"><br>
    <label for="address">
        Address:
    </label>
    <input type="text" name="address" id="address"><br>
    <label for="speciality">
        Speciality:
    </label>
    <input type="text" name="speciality" id="speciality"><br>
    <label for="name">
        Name:
    </label>
    <input type="text" name="name" id="name"><br>
    <label for="description">
        Description:
    </label>
    <input type="text" name="description" id="description"><br>
    <label for="price">
        Price:
    </label>
    <input type="number" name="price" id="price"><br>
    <label for="client">
        Client:
    </label>
    <input type="text" name="client" id="client"><br>
    <label for="employee">
        Employee:
    </label>
    <input type="text" name="employee" id="employee"><br>
    <label for="service">
        Service:
    </label>
    <input type="text" name="service" id="service"><br>
    <label for="date">
        Date:
    </label>
    <input type="number" name="date" id="date"><br>
  </fieldset>
  <input type="submit" value="Add">
</form>

Teme/tema14nou/site_programari/programari/templates/service_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ service.name }}</title>
</head>
<body>
{{ service }}
</body>
</html>