Sesiunea14/pet_adoption_agency/pet_adoption_agency/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("pets/", include("pets.urls"))  # din folderul pets se va include urls
]

Sesiunea14/pet_adoption_agency/pets/urls.py
from django.urls import path
from . import views # importam fisierul views

# definim lista pentru toate rutele care le accepta aplicatia noastra
# urlpatterns = [
#     path("", views.pets, name="all_pets"),  #prima pagina contine ruta, functia si numele rutei
#     path("<int:pet_id>", views.pet_details, name="pet_details"),
#     path("pet", views.pet_add, name="add")
# ]
urlpatterns = [
    path("", views.PetsView.as_view(), name="all_pets"),  #prima pagina contine ruta, functia si numele rutei
    path("<int:pk>", views.PetDetailView.as_view(), name="pet_details"),
    path("pet", views.PetCreateView.as_view(), name="add")
]
app_name = "pets" # ca aplicatia sa ruleze e necesar sa creeam obiect

Sesiunea14/pet_adoption_agency/pets/models.py
from django.db import models


# Create your models here.

class Pet(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField(null=False)
    gender = models.CharField(max_length=1, choices=[("F", "Female"), ("M", "Male")])  # lista cu tupluri
    species = models.CharField(max_length=6, choices=[("dog", "Dog"), ("cat", "Cat"), ("rabbit", "Rabbit")])

    def __str__(self):
        return f"{self.name} - {self.age} - {self.gender} - {self.species}"

Sesiunea14/pet_adoption_agency/pets/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from .models import Pet


# Create your views here.

# def index(request):
#     return HttpResponse("Hello World")
#
#
# def pets(request):
#     pets_list = Pet.objects.all()  # returneaza toate obiectele de tip Pet
#     return render(request, "all_pets.html", {"pets": pets_list})
#
#
# def pet_details(request, pet_id):
#     pet = get_object_or_404(Pet, pk=pet_id)  # pk=primary key - cheia dupa care sa ne caute
#     return render(request, "pet_details.html", {"pet": pet}) # pet_details.html fisier creat in templates
#
# def pet_add(request):
#     pet_details = request.POST.dict()
#     pet = Pet(name=pet_details["name"], age = pet_details["age"], gender = pet_details["gender"], species = pet_details["species"])
#     pet.save()
#     return HttpResponseRedirect(reverse("pets:all_pets"))

class PetsView(generic.ListView):
    template_name = "all_pets.html"
    context_object_name = "pets"

    def get_queryset(self):
        return Pet.objects.all()


class PetDetailView(generic.DetailView):
    template_name = "pet_details.html"
    model = Pet


class PetCreateView(generic.CreateView):
    model = Pet
    fields = ["name", "age", "gender", "species"]
    success_url = reverse_lazy("pets:all_pets")

Sesiunea14/pet_adoption_agency/pets/templates/all_pets.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Pets</title>
</head>
<body>
{% if pets %}
<h2>
    Pets up for adoption

</h2>
<div class ="pets-list">
    <ul>

        {% for pet in pets %}
        <li>
           <a href="{% url 'pets:pet_details' pet.id %}"> {{ pet }}</a>
        </li>
        {% endfor %}
    </ul>
    </div>
{% include "form.html" %}
{% endif %}
</body>
</html>

Sesiunea14/pet_adoption_agency/pets/templates/form.html
<form action="{% url 'pets:add' %}" method="post">
  {% csrf_token %}
  <fieldset>
      <label for="name">
          Name:
      </label>
    <input type="text" name="name" id="name"><br>
    <label for="age">
        Age:
    </label>
    <input type="number" name="age" id="age"><br>
    <label for="gender">
        Gender:
    </label>
    <label for="gender(F)">
       female
    </label>
    <input type="radio" name="gender" id="gender(F)" value="F">
    <label for="gender(M)">
       male
    </label>
    <input type="radio" name="gender" id="gender(M)" value="M"><br>
    <label for="species">
        Species:
    </label>
    <input type="text" name="species" id="species"><br>
  </fieldset>
  <input type="submit" value="Add">

</form>

Sesiunea14/pet_adoption_agency/pets/templates/pet_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ pet.name }}</title>
    {%comment va arata numele petului pe bara de sus la explorer %}
    {% endcomment %}
</head>
<body>
{{ pet }}
</body>
</html>